# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/jackson/Documents/projectempire/src/main/python/adminwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.stock_tab = QtWidgets.QWidget()
        self.stock_tab.setObjectName("stock_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.stock_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.stock_tab)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.product_table_view = QtWidgets.QTableView(self.frame)
        self.product_table_view.setObjectName("product_table_view")
        self.verticalLayout_2.addWidget(self.product_table_view)
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_product_button = QtWidgets.QPushButton(self.widget)
        self.add_product_button.setObjectName("add_product_button")
        self.horizontalLayout.addWidget(self.add_product_button)
        self.delete_product_button = QtWidgets.QPushButton(self.widget)
        self.delete_product_button.setObjectName("delete_product_button")
        self.horizontalLayout.addWidget(self.delete_product_button)
        self.verticalLayout_2.addWidget(self.widget)
        self.verticalLayout_3.addWidget(self.frame)
        self.tabWidget.addTab(self.stock_tab, "")
        self.users_tab = QtWidgets.QWidget()
        self.users_tab.setObjectName("users_tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.users_tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.users_tab)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.user_table_view = QtWidgets.QTableView(self.frame_2)
        self.user_table_view.setObjectName("user_table_view")
        self.verticalLayout_4.addWidget(self.user_table_view)
        self.widget_2 = QtWidgets.QWidget(self.frame_2)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.add_user_button = QtWidgets.QPushButton(self.widget_2)
        self.add_user_button.setObjectName("add_user_button")
        self.horizontalLayout_2.addWidget(self.add_user_button)
        self.delete_user_button = QtWidgets.QPushButton(self.widget_2)
        self.delete_user_button.setObjectName("delete_user_button")
        self.horizontalLayout_2.addWidget(self.delete_user_button)
        self.verticalLayout_4.addWidget(self.widget_2)
        self.verticalLayout_5.addWidget(self.frame_2)
        self.tabWidget.addTab(self.users_tab, "")
        self.orders_tab = QtWidgets.QWidget()
        self.orders_tab.setObjectName("orders_tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.orders_tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.orders_table_view = QtWidgets.QTableView(self.orders_tab)
        self.orders_table_view.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.orders_table_view.setObjectName("orders_table_view")
        self.verticalLayout_6.addWidget(self.orders_table_view)
        self.tabWidget.addTab(self.orders_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLog_Out = QtWidgets.QAction(MainWindow)
        self.actionLog_Out.setObjectName("actionLog_Out")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionLog_Out)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add_product_button.setText(_translate("MainWindow", "Add Product"))
        self.delete_product_button.setText(_translate("MainWindow", "Delete Product"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.stock_tab), _translate("MainWindow", "Product Stock"))
        self.add_user_button.setText(_translate("MainWindow", "Add User"))
        self.delete_user_button.setText(_translate("MainWindow", "Delete User"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.users_tab), _translate("MainWindow", "Users"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.orders_tab), _translate("MainWindow", "Orders"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionLog_Out.setText(_translate("MainWindow", "Log Out"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
